  - echo "solver.onlyRequires = true" >> /etc/zypp/zypp.conf
  - [ zypper, --gpg-auto-import-keys, ref ]
  - [ zypper, up, -y ]
  - [ zypper, -n, in, --recommends, -t, pattern, ${patterns} ]
  - [ zypper, -n, install, ${packages} ]
  - iptables-save | awk '/^[*]/ { print $1 "\nCOMMIT" }' | iptables-restore
  - lsmod | egrep ^iptable_ | awk '{print $1}' | xargs -rd\\n modprobe -r
  - sh -c 'echo root:${root_password} | chpasswd'
  - useradd -p ${root_password} tux
  - yast2 remote allow set=yes
  - yast2 rdp allow set=yes
  - git clone https://github.com/wiredquill/STW-CaaSPv4.git /home/ec2-user/STW-CaaSPv4/
  - touch /home/ec2-user/build_complete
