  - SUSEConnect --url https://scc.suse.com -r ${caasp_registry_code}
  - SUSEConnect -p sle-module-containers/15.1/x86_64
  - SUSEConnect -p sle-module-desktop-applications/15.1/x86_64
  - SUSEConnect -p sle-we/15.1/x86_64 -r  INTERNAL-USE-ONLY-c48e-dfaf
  - SUSEConnect -p caasp/4.0/x86_64 -r ${caasp_registry_code}
